"""Add testing fields to ComputerSystem model

Revision ID: 35e5807f55ee
Revises: c24d97f2675d
Create Date: 2025-02-06 12:47:34.477293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e5807f55ee'
down_revision = 'c24d97f2675d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computer_systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu_benchmark', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('usb_ports_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('usb_ports_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('video_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('network_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('network_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('general_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tested_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['tested_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('computer_systems', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tested_by')
        batch_op.drop_column('general_notes')
        batch_op.drop_column('network_notes')
        batch_op.drop_column('network_status')
        batch_op.drop_column('video_notes')
        batch_op.drop_column('video_status')
        batch_op.drop_column('usb_ports_notes')
        batch_op.drop_column('usb_ports_status')
        batch_op.drop_column('cpu_benchmark')

    # ### end Alembic commands ###
