"""Add barcode and product info fields

Revision ID: 526c5315e554
Revises: c8a18f1acdb4
Create Date: 2024-12-08 11:33:42.890174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c5315e554'
down_revision = 'c8a18f1acdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('mpn', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=512), nullable=True))
        batch_op.create_unique_constraint(None, ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image_url')
        batch_op.drop_column('mpn')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('description')
        batch_op.drop_column('barcode')

    # ### end Alembic commands ###
