"""add color field to tags

Revision ID: 7e2352cf0b03
Revises: add_system_tags
Create Date: 2025-01-23 11:21:33.005703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2352cf0b03'
down_revision = 'add_system_tags'
branch_labels = None
depends_on = None


def upgrade():
    # Add color column as nullable first
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))
    
    # Update existing rows with default color
    op.execute("UPDATE tag SET color = '#6c757d' WHERE color IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.String(length=7),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
