"""Add storage_location field

Revision ID: 86374a83f06c
Revises: 526c5315e554
Create Date: 2024-12-08 12:06:41.566292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86374a83f06c'
down_revision = '526c5315e554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_location', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_column('storage_location')

    # ### end Alembic commands ###
