"""Add roadmap votes table

Revision ID: 9415b4889fc3
Revises: 2cdd1e3bf864
Create Date: 2025-01-10 10:34:42.414919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9415b4889fc3'
down_revision = '2cdd1e3bf864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_votes',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['roadmap_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'user_id')
    )
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roadmap_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('roadmap_votes')
    # ### end Alembic commands ###
